### PR TITLE
optimizations, bug fixes, refactoring, removed non-ARC code

### PR DESCRIPTION
**Pull request by jessesquires**

### CODE REVIEW

**Comment by wuf810** [comment]
Great changes by jessesquires. Matt please accept this pull request!

**Comment by jessesquires** [comment]
nice! thanks @wuf810 and @mattlawer. thought this project had been abandoned. :) you might want to edit your README.

also, @mattlawer, would you consider switching to the [MIT License](http://opensource.org/licenses/MIT) for this?

**Comment by mattlawer** [comment]
I've a lot of work and not so much time to merge commits but I do it when I can.
The project is now under [MIT License](http://opensource.org/licenses/MIT) :)
Thanks @jessesquires for your interest and your work in this project !

**Comment by jessesquires** [comment]
Great! No, thank you! :) Awesome work @mattlawer.

**Comment by jessesquires** [comment]
Oh, one last thing. Would you mind linking to me in the readme? :)

Refactored by [@jessesquires](http://github.com/jessesquires), April 2013.

**Pull request merged**
